name: chatgpt_course
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  widget_and_text_animator: ^1.0.9
  rolling_bottom_bar: ^0.2.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  flutter_phoenix: ^1.1.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_langdetect: ^0.0.1
  fluttertoast: ^8.1.3
  device_info: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.8.2
  platform: ^3.1.3
  adaptive_theme: ^3.2.1
  injectable: ^2.1.1
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  awesome_dialog: ^3.1.0
  firebase_messaging: ^14.6.8
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  card_swiper: ^2.0.4
  cached_network_image: ^3.2.3
  flutter_paypal: ^0.0.8
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^16.1.0
  image_picker: ^0.8.7+5
  dio: ^5.3.3
  share: ^2.0.4
  path_provider:
  flutter_tesseract_ocr:
  permission_handler:
  image_cropper: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.4
  injectable_generator: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_img.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/
    - assets/
    - assets/tessdata/
